"use client";

type RelatedStore = { sales: { id: string; customer: string; items: string; date: string; total: number }[]; quotes: { number: string; customer: string; issueDate: string; status: string }[]; invoices: { number: string; customer: string; issueDate: string; status: string }[]; repairs: { id: string; customer: string; item: string; status: string }[]; laybys: { id: string; customer: string; item: string; total: number; paid: number; status: string }[]; appraisals: { id: string; customer: string; item: string; date: string; valuation: number }[]; communications: { id: string; customer: string; date: string; channel: string; subject: string }[]; followUps: { id: string; customer: string; dueDate: string; task: string; status: string }[] };
const money = (value: number) => new Intl.NumberFormat("en-ZA", { style: "currency", currency: "ZAR", maximumFractionDigits: 0 }).format(value);
const dateLabel = (value: string) => value ? new Intl.DateTimeFormat("en-ZA", { day: "2-digit", month: "short", year: "numeric" }).format(new Date(`${value}T12:00:00`)) : "-";

export function CustomerRelatedRecords({ store, customer }: { store: RelatedStore; customer: string }) {
  const records = { quotes: store.quotes.filter((item) => item.customer === customer), invoices: store.invoices.filter((item) => item.customer === customer), repairs: store.repairs.filter((item) => item.customer === customer), laybys: store.laybys.filter((item) => item.customer === customer), appraisals: store.appraisals.filter((item) => item.customer === customer), communications: store.communications.filter((item) => item.customer === customer), followUps: store.followUps.filter((item) => item.customer === customer) };
  return <div className="customer-related-grid"><section><h3>Quotes</h3>{records.quotes.map((item) => <div className="history-row" key={item.number}><span>{item.number}<small>{dateLabel(item.issueDate)}</small></span><strong>{item.status}</strong></div>)}{!records.quotes.length && <small>No quotes</small>}</section><section><h3>Invoices</h3>{records.invoices.map((item) => <div className="history-row" key={item.number}><span>{item.number}<small>{dateLabel(item.issueDate)}</small></span><strong>{item.status}</strong></div>)}{!records.invoices.length && <small>No invoices</small>}</section><section><h3>Repairs</h3>{records.repairs.map((item) => <div className="history-row" key={item.id}><span>{item.item}<small>{item.id}</small></span><strong>{item.status}</strong></div>)}{!records.repairs.length && <small>No repairs</small>}</section><section><h3>Lay-bys</h3>{records.laybys.map((item) => <div className="history-row" key={item.id}><span>{item.item}<small>{item.id}</small></span><strong>{money(item.total - item.paid)}</strong></div>)}{!records.laybys.length && <small>No lay-bys</small>}</section><section><h3>Appraisals</h3>{records.appraisals.map((item) => <div className="history-row" key={item.id}><span>{item.item}<small>{item.id} · {dateLabel(item.date)}</small></span><strong>{money(item.valuation)}</strong></div>)}{!records.appraisals.length && <small>No appraisals</small>}</section><section><h3>Communication log</h3>{records.communications.map((item) => <div className="history-row" key={item.id}><span>{item.subject}<small>{item.channel} · {dateLabel(item.date)}</small></span></div>)}{!records.communications.length && <small>No communications</small>}</section><section><h3>Follow-up tasks</h3>{records.followUps.map((item) => <div className="history-row" key={item.id}><span>{item.task}<small>Due {dateLabel(item.dueDate)}</small></span><strong>{item.status}</strong></div>)}{!records.followUps.length && <small>No follow-ups</small>}</section></div>;
}
