"use client";

type ReportStore = { sales: { date: string; customer: string; total: number; method: string; profit: number }[]; invoices: { number: string; customer: string; issueDate: string; payments: { amount: number; method: string }[]; lines: { quantity: number; unitPrice: number; vatApplicable: boolean }[] }[]; products: { name: string; cost: number; stock: number }[]; repairs: { id: string; customer: string; status: string; due: string }[]; laybys: { id: string; customer: string; total: number; paid: number; status: string }[]; followUps: { id: string; customer: string; dueDate: string; task: string; status: string }[] };
const money = (value: number) => new Intl.NumberFormat("en-ZA", { style: "currency", currency: "ZAR", maximumFractionDigits: 0 }).format(value);
const dateLabel = (value: string) => new Intl.DateTimeFormat("en-ZA", { day: "2-digit", month: "short", year: "numeric" }).format(new Date(`${value}T12:00:00`));

export function ReportBreakdown({ store }: { store: ReportStore }) {
  const vatRate = 0.15; const vatRows = store.invoices.map((invoice) => { const net = invoice.lines.reduce((sum, line) => sum + line.quantity * line.unitPrice, 0); return { invoice: invoice.number, customer: invoice.customer, date: invoice.issueDate, net, vat: net * vatRate, total: net * (1 + vatRate) }; });
  const methods = ["Cash", "Card", "EFT", "Split"].map((method) => ({ method, count: store.sales.filter((sale) => sale.method === method).length, total: store.sales.filter((sale) => sale.method === method).reduce((sum, sale) => sum + sale.total, 0) }));
  const download = (filename: string, rows: string[][]) => { const csv = rows.map((row) => row.map((cell) => `"${cell.replaceAll('"', '""')}"`).join(",")).join("\n"); const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([csv], { type: "text/csv" })); link.download = filename; link.click(); URL.revokeObjectURL(link.href); };
  return <div className="report-two"><section className="panel table-panel"><div className="panel-head"><div><h2>VAT report</h2><p>Invoice net, VAT and gross totals at 15%</p></div><button className="text-btn" onClick={() => download("vat-report.csv", [["Invoice", "Customer", "Date", "Net", "VAT", "Total"], ...vatRows.map((row) => [row.invoice, row.customer, row.date, String(row.net), String(row.vat), String(row.total)])])}>Export CSV</button></div><table><thead><tr><th>Invoice</th><th>Customer</th><th>Date</th><th>Net</th><th>VAT</th><th>Total</th></tr></thead><tbody>{vatRows.map((row) => <tr key={row.invoice}><td>{row.invoice}</td><td>{row.customer}</td><td>{dateLabel(row.date)}</td><td>{money(row.net)}</td><td>{money(row.vat)}</td><td><strong>{money(row.total)}</strong></td></tr>)}</tbody></table></section><section className="panel table-panel"><div className="panel-head"><div><h2>Payment methods</h2><p>Sales count and value by tender type</p></div><button className="text-btn" onClick={() => download("payment-methods.csv", [["Method", "Count", "Total"], ...methods.map((row) => [row.method, String(row.count), String(row.total)])])}>Export CSV</button></div><table><thead><tr><th>Method</th><th>Transactions</th><th>Total</th></tr></thead><tbody>{methods.map((row) => <tr key={row.method}><td>{row.method}</td><td>{row.count}</td><td><strong>{money(row.total)}</strong></td></tr>)}</tbody></table></section><section className="panel table-panel"><div className="panel-head"><div><h2>CRM follow-ups & reminders</h2><p>Open tasks, repair deadlines and lay-by balances</p></div><button className="text-btn" onClick={() => download("crm-follow-ups.csv", [["Customer", "Due", "Task", "Status"], ...store.followUps.map((row) => [row.customer, row.dueDate, row.task, row.status])])}>Export CSV</button></div><table><thead><tr><th>Customer</th><th>Due</th><th>Task</th><th>Status</th></tr></thead><tbody>{store.followUps.map((row) => <tr key={row.id}><td>{row.customer}</td><td>{dateLabel(row.dueDate)}</td><td>{row.task}</td><td>{row.status}</td></tr>)}{store.repairs.map((row) => <tr key={row.id}><td>{row.customer}</td><td>{dateLabel(row.due)}</td><td>Repair {row.id}: {row.status}</td><td>Open</td></tr>)}{store.laybys.map((row) => <tr key={row.id}><td>{row.customer}</td><td>-</td><td>Lay-by balance {money(row.total - row.paid)}</td><td>{row.status}</td></tr>)}</tbody></table></section></div>;
}
